# Generated by Django 4.1.4 on 2022-12-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_homebanner_authors_homebanner_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ky',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
