# Generated by Django 4.1.4 on 2022-12-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0014_contactsphone_faqs_en_contactsphone_faqs_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотип'},
        ),
    ]
