# Generated by Django 4.1.4 on 2022-12-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_alter_contacts_options_alter_contactsphone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнеры', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
