# Generated by Django 4.1.4 on 2022-12-31 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0017_alter_partner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Главная - О журнале', 'verbose_name_plural': 'Главная - О журнале'},
        ),
        migrations.AlterModelOptions(
            name='homeafisha',
            options={'verbose_name': 'Главная - Афиша', 'verbose_name_plural': 'Главная - Афиша'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': 'Банеры', 'verbose_name_plural': 'Банеры'},
        ),
        migrations.AlterModelOptions(
            name='homebook',
            options={'verbose_name': 'Главная - Книга', 'verbose_name_plural': 'Главная - Книга'},
        ),
        migrations.AlterModelOptions(
            name='homecomment',
            options={'verbose_name': 'Главная - Комментарии', 'verbose_name_plural': 'Главная - Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='homestatistic',
            options={'verbose_name': 'Главная - Статистика', 'verbose_name_plural': 'Главная - Статистика'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name': 'Выпуски - Категории', 'verbose_name_plural': 'Выпуски - Категории'},
        ),
        migrations.AlterModelOptions(
            name='issuescategory',
            options={'verbose_name': 'Выпуски - Категории', 'verbose_name_plural': 'Выпуски - Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Главная - Новости', 'verbose_name_plural': 'Главная - Новости'},
        ),
    ]
