# Generated by Django 4.1.4 on 2023-01-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0018_alter_homeabout_options_alter_homeafisha_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeacademy',
            options={'verbose_name': 'Манас академия', 'verbose_name_plural': 'Манас академия'},
        ),
    ]
